version: '2'
services:
  web:
    build: ./angular-app
    ports:
    - "80:80"
    links:
    - node
    volumes:
    - "~/coderbro_code/docker-mean-aws/angular-app/dist:/usr/share/nginx/html"
  node:
    build: ./node-app
    ports:
    - "3000:3000"
    links:
    - mongo
  mongo:
    image: mongo
    ports: 
    - "27017:27017"
